name: Build & Deploy to GKE

on:
  push:
    branches:
      - main

env:
  ARTIFACT_REGISTRY_LOCATION: us-east1
  ARTIFACT_REPO: wisecow-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Install GKE auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker ${ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev -q

      - name: Build and push Docker image
        env:
          IMAGE: ${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.ARTIFACT_REPO }}/wisecow
        run: |
          docker build -t $IMAGE:latest .
          docker tag $IMAGE:latest $IMAGE:${GITHUB_SHA}
          docker push $IMAGE:latest
          docker push $IMAGE:${GITHUB_SHA}
          echo "IMAGE=$IMAGE:${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
            --region ${{ secrets.GKE_LOCATION }} \
            --project ${{ secrets.GCP_PROJECT }}

      - name: Update k8s manifest with new image and apply
        run: |
          IMAGE_FULL=${{ env.IMAGE }}
          mkdir -p tmp_manifests
          cp -r k8s/* tmp_manifests/
          sed -i "s|us-east1-docker.pkg.dev/PROJECT_ID/wisecow-repo/wisecow:latest|$IMAGE_FULL|g" tmp_manifests/deployment.yaml || true
          kubectl apply -f tmp_manifests/
          kubectl set image deployment/wisecow-deployment wisecow=$IMAGE_FULL --record || true
